import { useEffect, useRef } from 'react';
import L from 'leaflet';
import { Circle, MapContainer, Marker, Popup, TileLayer, Tooltip, useMap } from 'react-leaflet';
import { getFacilityBrandIcon } from '../domain/brandIcons';
import { formatDistance } from '../domain/distance';
import { text, vacancyLabel, type Language } from '../i18n';
import type { Coordinates, NearbyFacility, NearbyFacilityViewModel, OnStreetParkingGroup, OnStreetParkingViewModel, ParkViewModel, PublicToilet, PublicToiletViewModel } from '../types';
import { washroomSymbolMarkup } from './WashroomSymbol';

type Props = { language: Language; position: Coordinates; parks: ParkViewModel[]; nearbyItems: Array<PublicToiletViewModel | NearbyFacilityViewModel | OnStreetParkingViewModel>; selectedId: string | null; lastViewedParkId: string | null; lastViewedOnStreetId: string | null; onSelect: (id: string) => void; onSelectOnStreet: (id: string) => void; onLocationSelect: (coordinates: Coordinates, behavior: { recenter: boolean }) => void; recenterRequest: number; startupLocating: boolean; startupRecenter: boolean; expanded: boolean; onToggleExpanded: () => void; onShowResults: () => void; resultsLabel: string };

const LANDSD_BASEMAP_URL = 'https://mapapi.geodata.gov.hk/gs/api/v1.0.0/xyz/basemap/WGS84/{z}/{x}/{y}.png';
const LANDSD_LABEL_URL = 'https://mapapi.geodata.gov.hk/gs/api/v1.0.0/xyz/label/hk/tc/WGS84/{z}/{x}/{y}.png';
const LANDSD_MIN_NATIVE_ZOOM = 10;
const LANDSD_MAX_NATIVE_ZOOM = 20;
const MAP_MAX_ZOOM = 22;
const LANDSD_LOGO_URL = 'https://api.hkmapservice.gov.hk/mapapi/landsdlogo.jpg';

function Recenter({ position, request, startup }: { position: Coordinates; request: number; startup: boolean }) { const map = useMap(); const startupFlightUsed = useRef(false); useEffect(() => { if (request === 0) return; if (startup && !startupFlightUsed.current) { startupFlightUsed.current = true; map.flyTo([position.lat, position.lng], 14, { duration: 1.4 }); return; } map.setView([position.lat, position.lng], 14, { animate: true }); }, [map, position.lat, position.lng, request, startup]); return null; }
function FocusSelected({ park }: { park?: ParkViewModel }) { const map = useMap(); useEffect(() => { if (park) map.flyTo([park.info.latitude, park.info.longitude], Math.max(map.getZoom(), 15), { duration: 0.35 }); }, [map, park]); return null; }
function ResizeMap({ expanded }: { expanded: boolean }) { const map = useMap(); useEffect(() => { const timer = window.setTimeout(() => map.invalidateSize({ animate: true }), 220); return () => window.clearTimeout(timer); }, [expanded, map]); return null; }

function LongPressPicker({ onPick }: { onPick: (coordinates: Coordinates) => void }) {
  const map = useMap();
  useEffect(() => {
    const container = map.getContainer(); let timer: number | undefined; let start: { x: number; y: number } | undefined; let startView: { center: L.LatLng; zoom: number } | undefined; let dragLocked = false; let draggingWasEnabled = false;
    const isBlocked = (target: EventTarget | null) => target instanceof Element && Boolean(target.closest('.leaflet-marker-icon, .leaflet-control'));
    const cancel = () => { if (timer !== undefined) window.clearTimeout(timer); timer = undefined; start = undefined; startView = undefined; };
    const finish = () => { cancel(); if (dragLocked && draggingWasEnabled) map.dragging.enable(); dragLocked = false; draggingWasEnabled = false; };
    const begin = (x: number, y: number, target: EventTarget | null) => { if (isBlocked(target)) return; start = { x, y }; startView = { center: map.getCenter(), zoom: map.getZoom() }; draggingWasEnabled = map.dragging.enabled(); timer = window.setTimeout(() => { if (!start || !startView) return; map.stop(); map.setView(startView.center, startView.zoom, { animate: false }); if (draggingWasEnabled) { map.dragging.disable(); dragLocked = true; } const bounds = container.getBoundingClientRect(); const size = map.getSize(); const latLng = map.containerPointToLatLng([(x - bounds.left) * (size.x / bounds.width), (y - bounds.top) * (size.y / bounds.height)]); onPick({ lat: latLng.lat, lng: latLng.lng }); window.navigator.vibrate?.(18); cancel(); }, 700); };
    const move = (x: number, y: number) => { if (start && Math.hypot(x - start.x, y - start.y) > 12) cancel(); };
    const touchStart = (event: TouchEvent) => { const touch = event.touches[0]; if (touch) begin(touch.clientX, touch.clientY, event.target); }; const touchMove = (event: TouchEvent) => { const touch = event.touches[0]; if (touch) move(touch.clientX, touch.clientY); }; const mouseDown = (event: MouseEvent) => { if (event.button === 0) begin(event.clientX, event.clientY, event.target); }; const mouseMove = (event: MouseEvent) => move(event.clientX, event.clientY); const preventContextMenu = (event: Event) => event.preventDefault();
    container.addEventListener('touchstart', touchStart, { passive: true }); container.addEventListener('touchmove', touchMove, { passive: true }); container.addEventListener('touchend', finish); container.addEventListener('touchcancel', finish); container.addEventListener('mousedown', mouseDown); container.addEventListener('mousemove', mouseMove); container.addEventListener('mouseup', finish); container.addEventListener('mouseleave', finish); container.addEventListener('contextmenu', preventContextMenu);
    return () => { finish(); container.removeEventListener('touchstart', touchStart); container.removeEventListener('touchmove', touchMove); container.removeEventListener('touchend', finish); container.removeEventListener('touchcancel', finish); container.removeEventListener('mousedown', mouseDown); container.removeEventListener('mousemove', mouseMove); container.removeEventListener('mouseup', finish); container.removeEventListener('mouseleave', finish); container.removeEventListener('contextmenu', preventContextMenu); };
  }, [map, onPick]); return null;
}

function markerIcon(park: ParkViewModel, language: Language, lastViewed: boolean) { const label = park.status.kind === 'count' ? String(park.status.count) : park.status.kind === 'available' ? (language === 'en' ? 'A' : '有') : park.status.kind === 'full' ? (language === 'en' ? 'F' : '滿') : park.status.kind === 'closed' ? (language === 'en' ? 'C' : '關') : '–'; return L.divIcon({ className: 'parking-marker-shell', html: `<span class="parking-marker marker-${park.status.kind}${lastViewed ? ' is-last-viewed' : ''}"><b>${label}</b></span>`, iconSize: [38, 38], iconAnchor: [19, 38] }); }
const selectedCenterIcon = L.divIcon({ className: 'selected-center-marker-shell', html: '<span class="selected-center-marker" aria-hidden="true">📍</span>', iconSize: [32, 36], iconAnchor: [16, 36] });
function nearbyIcon(kind?: PublicToilet['kind'] | NearbyFacility['kind'] | OnStreetParkingGroup['kind'], occupancy?: OnStreetParkingGroup['occupancy'], vacant?: number, brand?: string, lastViewed = false, staticRoadside = false, total = 0, venueLocation = false) {
  const venue = kind === 'lcsdVenue' || venueLocation; const fuel = kind === 'fuel'; const atm = kind === 'atm'; const motorcycle = kind === 'motorcycle'; const onStreet = kind === 'metered' || kind === 'nonMetered' || motorcycle; const washroom = !fuel && !atm && !onStreet; const brandIcon = fuel || atm ? getFacilityBrandIcon(fuel ? 'fuel' : 'atm', brand) : undefined; const count = staticRoadside ? total : vacant ?? 0; const label = onStreet ? String(count > 99 ? '99+' : count) : washroom ? washroomSymbolMarkup(venue) : fuel ? '⛽' : '🏧'; const content = brandIcon ? `<span class="facility-brand-mark" aria-hidden="true"><img src="${brandIcon.src}" alt="" /></span>` : `<span aria-hidden="true">${label}</span>`; return L.divIcon({ className: 'toilet-marker-shell', html: `<span class="toilet-marker${venue ? ' is-venue' : fuel ? ' is-fuel' : atm ? ' is-atm' : onStreet ? ` is-onstreet is-${occupancy}${motorcycle ? ' is-motorcycle' : ''}` : ''}${brandIcon ? ' is-brand' : ''}${lastViewed ? ' is-last-viewed' : ''}">${content}</span>`, iconSize: [34, 34], iconAnchor: [17, 34] });
}
function MapFocusIcon({ expanded }: { expanded: boolean }) { return expanded ? <svg className="map-focus-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 3 3 3 3-3M9 21l3-3 3 3M3 9l3 3-3 3M21 9l-3 3 3 3" /></svg> : <svg className="map-focus-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3H3v6m0-6 7 7M15 3h6v6m0-6-7 7M9 21H3v-6m0 6 7-7m5 7h6v-6m0 6-7-7" /></svg>; }

export function MapView({ language, position, parks, nearbyItems, selectedId, lastViewedParkId, lastViewedOnStreetId, onSelect, onSelectOnStreet, onLocationSelect, recenterRequest, startupLocating, startupRecenter, expanded, onToggleExpanded, onShowResults, resultsLabel }: Props) {
  const selected = parks.find((park) => park.info.park_Id === selectedId); const visibleResultCount = parks.length + nearbyItems.length;
  const label = (kind?: PublicToilet['kind'] | NearbyFacility['kind'] | OnStreetParkingGroup['kind']) => kind === 'lcsdVenue' ? text(language, 'venueWashroom') : kind === 'lcsdParkToilet' ? text(language, 'lcsdParkWashroom') : kind === 'afcdCountryParkToilet' ? text(language, 'afcdCountryParkWashroom') : kind === 'fuel' ? (language === 'en' ? 'Consumer Council fuel station' : '消委會油站') : kind === 'atm' ? (language === 'en' ? 'HKMA ATM' : '金管局 ATM') : kind === 'metered' ? text(language, 'meteredParking') : kind === 'nonMetered' ? text(language, 'nonMeteredTrial') : kind === 'motorcycle' ? text(language, 'motorcycleOnStreet') : text(language, 'publicToilet');
  return <div className={expanded ? 'map-wrap is-expanded' : 'map-wrap'} aria-label={text(language, 'mapLabel')}><MapContainer center={[position.lat, position.lng]} zoom={startupLocating ? 10 : 14} minZoom={8} maxZoom={MAP_MAX_ZOOM} scrollWheelZoom inertia={false} className="landsd-map"><TileLayer minNativeZoom={LANDSD_MIN_NATIVE_ZOOM} maxNativeZoom={LANDSD_MAX_NATIVE_ZOOM} maxZoom={MAP_MAX_ZOOM} attribution='&copy; <a href="https://api.portal.hkmapservice.gov.hk/disclaimer" target="_blank" rel="noreferrer">Map information from Lands Department</a>' url={LANDSD_BASEMAP_URL} /><TileLayer minNativeZoom={LANDSD_MIN_NATIVE_ZOOM} maxNativeZoom={LANDSD_MAX_NATIVE_ZOOM} maxZoom={MAP_MAX_ZOOM} url={LANDSD_LABEL_URL} opacity={1} zIndex={10} /><Recenter position={position} request={recenterRequest} startup={startupRecenter} /><FocusSelected park={selected} /><ResizeMap expanded={expanded} /><LongPressPicker onPick={(coordinates) => onLocationSelect(coordinates, { recenter: false })} />{!startupLocating && <><Circle center={[position.lat, position.lng]} radius={2_000} pathOptions={{ color: '#14B8A6', fillColor: '#14B8A6', fillOpacity: 0.1, weight: 2, dashArray: '6 6' }} /><Marker position={[position.lat, position.lng]} icon={selectedCenterIcon} zIndexOffset={1_000} keyboard={false} /></>}{parks.map((park) => <Marker key={park.info.park_Id} position={[park.info.latitude, park.info.longitude]} icon={markerIcon(park, language, park.info.park_Id === lastViewedParkId)} zIndexOffset={park.info.park_Id === lastViewedParkId ? 600 : 0} eventHandlers={{ click: () => onSelect(park.info.park_Id) }}><Tooltip direction="top" offset={[0, -38]} opacity={0.95}>{park.info.name} · {vacancyLabel(language, park.status)}</Tooltip></Marker>)}{nearbyItems.map((item) => {
    const onStreet = 'onStreet' in item ? item.onStreet : undefined;
    const place = 'toilet' in item ? item.toilet : 'facility' in item ? item.facility : onStreet!;
    const venueLocation = 'toilet' in item && (item.toilet.locationPrecision === 'venue' || item.toilet.kind === 'lcsdVenue');
    const travel = place.kind === 'fuel' || onStreet ? '&travelmode=driving' : place.kind === 'atm' ? '&travelmode=walking' : '';
    const directions = place.kind === 'fuel' || onStreet ? text(language, 'drivingNavigation') : place.kind === 'atm' ? text(language, 'walkingNavigation') : venueLocation ? text(language, 'navigateToVenue') : text(language, 'navigation');
    const extra = onStreet ? (onStreet.static ? text(language, 'motorcycleOnStreetNoLive') : text(language, 'onStreetSpaceSummary', { vacant: onStreet.vacant, total: onStreet.total, occupied: onStreet.occupied, unavailable: onStreet.unavailable })) : 'openingHours' in place ? place.openingHours ?? text(language, 'openingUnavailable') : text(language, 'openingUnavailable');
    const isLastViewed = onStreet?.id === lastViewedOnStreetId; const brand = 'brand' in place ? place.brand : undefined;
    return <Marker key={place.id} position={[place.latitude, place.longitude]} icon={nearbyIcon(place.kind, onStreet?.occupancy, onStreet?.vacant, brand, isLastViewed, onStreet?.static, onStreet?.total, venueLocation)} zIndexOffset={isLastViewed ? 600 : 300} eventHandlers={onStreet ? { click: () => onSelectOnStreet(onStreet.id) } : undefined}>{!onStreet && <Popup><div className="toilet-popup"><strong>{place.name}</strong><small>{label(place.kind)}</small><small>{venueLocation ? text(language, 'distanceToVenue', { value: formatDistance(item.distanceKm) }) : formatDistance(item.distanceKm)} · {extra}</small>{venueLocation && <small>{text(language, 'venueLocationPrecision')}</small>}{place.address && <small>{place.address}</small>}<a href={`https://www.google.com/maps/dir/?api=1&destination=${place.latitude},${place.longitude}${travel}`} target="_blank" rel="noreferrer">{directions}</a></div></Popup>}</Marker>;
  })}</MapContainer>{startupLocating && <div className="map-startup-location-state" role="status" aria-live="polite"><span className="loader" /><span>{text(language, 'startupLocationLoading')}</span></div>}<button className="map-focus-toggle" type="button" onClick={onToggleExpanded} aria-pressed={expanded} aria-label={expanded ? text(language, 'mapCollapse') : text(language, 'mapExpand')} title={expanded ? text(language, 'mapCollapse') : text(language, 'mapExpand')}><MapFocusIcon expanded={expanded} /></button>{!expanded && visibleResultCount > 0 && <button className="map-results-link" type="button" onClick={onShowResults}>{text(language, 'showResults', { count: resultsLabel })}</button>}<a className="landsd-credit" href="https://api.portal.hkmapservice.gov.hk/disclaimer" target="_blank" rel="noreferrer"><span>{text(language, 'landsdCredit')}</span><img src={LANDSD_LOGO_URL} alt={text(language, 'landsdLogo')} /></a></div>;
}
