import { useState } from 'react';
import { isStaticPages } from '../api/site';
import { formatDistance } from '../domain/distance';
import { usePlacePhoto } from '../hooks/usePlacePhoto';
import { text, type Language } from '../i18n';
import type { PublicToiletViewModel } from '../types';

type Props = { language: Language; toilet: PublicToiletViewModel };

export function ToiletCard({ language, toilet: { toilet, distanceKm } }: Props) {
  const navigationUrl = `https://www.google.com/maps/dir/?api=1&destination=${toilet.latitude},${toilet.longitude}`;
  const isLcsdVenue = toilet.kind === 'lcsdVenue';
  const [showPhoto, setShowPhoto] = useState(false);
  const [photoState, setPhotoState] = usePlacePhoto({ id: toilet.id, name: toilet.name, address: toilet.address, latitude: toilet.latitude, longitude: toilet.longitude }, showPhoto && !isStaticPages);
  const source = isLcsdVenue ? text(language, 'venueWashroom') : text(language, 'publicToilet');

  return <article className="toilet-card"><div className="toilet-card-main"><div className="card-heading"><span className={isLcsdVenue ? 'toilet-card-icon is-venue' : 'toilet-card-icon'} aria-hidden="true">{isLcsdVenue ? '🏟️' : '🚻'}</span><div><h3>{toilet.name}</h3><p>{toilet.address ?? (isLcsdVenue ? text(language, 'venue') : text(language, 'publicToilet'))}</p></div><span className="distance">{formatDistance(distanceKm)}</span></div><div className="toilet-facts"><span className={isLcsdVenue ? 'washroom-source is-venue' : 'washroom-source'}>{source}</span><span>{toilet.openingHours ? text(language, 'opening', { value: toilet.openingHours }) : text(language, 'openingUnavailable')}</span>{toilet.remarks && <span>{toilet.remarks}</span>}</div>{showPhoto && !isStaticPages && <section className="toilet-photo-section" aria-live="polite">{photoState.kind === 'loading' && <p className="photo-state">{text(language, 'searchingPhoto')}</p>}{photoState.kind === 'found' && <figure className="toilet-photo"><img src={photoState.photo.photoUrl} alt={`${toilet.name} ${text(language, 'nearbyPhoto')}`} loading="lazy" onError={() => setPhotoState({ kind: 'unavailable', placeUrl: photoState.photo.placeUrl })} /><figcaption>{language === 'en' ? `${photoState.photo.distanceMeters} m away · ${photoState.photo.attribution}` : `相距約 ${photoState.photo.distanceMeters} 米 · ${photoState.photo.attribution} 提供`}</figcaption></figure>}{photoState.kind === 'not_found' && <p className="photo-state">{text(language, 'noVerifiedPhoto')}</p>}{photoState.kind === 'unavailable' && <p className="photo-state">{text(language, 'photoUnavailable')}</p>}{photoState.kind === 'found' && <a className="photo-link" href={photoState.photo.placeUrl} target="_blank" rel="noreferrer">{text(language, 'morePhotos')}</a>}{(photoState.kind === 'not_found' || photoState.kind === 'unavailable') && <a className="photo-link" href={photoState.placeUrl} target="_blank" rel="noreferrer">{text(language, 'morePhotos')}</a>}</section>}</div><div className="toilet-card-actions">{isStaticPages ? toilet.photoPlaceUrl ? <a className="toilet-photo-toggle" href={toilet.photoPlaceUrl} target="_blank" rel="noreferrer" aria-label={`${text(language, 'verifiedPhoto')}: ${toilet.name}`}>{text(language, 'verifiedPhoto')}</a> : <span className="toilet-photo-unavailable">{text(language, 'noPhoto')}</span> : <button className="toilet-photo-toggle" type="button" onClick={() => setShowPhoto((current) => !current)} aria-expanded={showPhoto}>{showPhoto ? text(language, 'collapse') : text(language, 'photo')}</button>}<a className="nav-link" href={navigationUrl} target="_blank" rel="noreferrer" aria-label={`${text(language, 'navigation')}: ${toilet.name}`}>{text(language, 'navigation')}</a></div></article>;
}
